"""Static CharacterID -> display-name lookup for Palworld pals.

Palworld's Level.sav stores each pal's species as an internal CharacterID
(e.g. "SheepBall") rather than the name players see in-game (e.g. "Lamball").
This table maps those internal IDs to their English display names so
diff.py's events are human-readable without a runtime dependency on game
data files.

Source: Palworld's own English localization strings, as tabulated by the
community-maintained Palworld-Pal-Editor project
(https://github.com/KrisCris/Palworld-Pal-Editor,
src/palworld_pal_editor/assets/data/pal_data.json). Includes base pals,
elemental/rare variants (e.g. "_Ice", "_Dark"), and field-boss/alpha
variants (BOSS_/PREDATOR_/GYM_/RAID_ prefixes) since captured alpha pals
keep those prefixed CharacterIDs. Regenerate by re-pulling that file's
InternalName -> I18n.en fields if the game adds new pals.

The upstream table predates the Palworld 1.0 content update, which added
~230 new CharacterIDs (new species, elemental variants, and field-boss/
predator titles). Those were backfilled from paldb.cc (https://paldb.cc)
instead: base species and simple elemental variants from its pal list page,
BOSS_/PREDATOR_ titles from each pal's own page's "Tribes" table, and
GYM_/RAID_/POLICE_ entries individually. A residual handful of CharacterIDs
are deliberately left unmapped (falling back to the raw CharacterID) because
paldb.cc itself has no real English name for them yet -- likely very-new or
unrevealed content: ArmorWoodlouse, BeardedDragon, BlueWoolRabbit,
CandleWitch, CuteOrca, ElecSnail_Fire, FrozenBear, GrassDragon, IceVeilDragon,
KingCrab, LeafBird, MedjedBird, MexicanSalamander, Monkey_Ice,
MonochromeMushroom, PinkKangaroo, RockCheetah, Sekhmet, SnakeQueen,
StrawHatCat, VolcanicTurtle, WaterLizard (plus their BOSS_ variants), the
field-boss-less BOSS_KingWhale, and the PREDATOR_*_Quest scripted-encounter
variants (FlowerRabbit/Garm/PinkLizard/Umihebi_Fire/WhiteShieldDragon), whose
titles aren't confirmed. Regenerate/extend by re-checking paldb.cc's pal
list and individual pal pages when the game adds more pals.
"""

PAL_NAMES = {
    'Alpaca': 'Melpaca',
    'AmaterasuWolf': 'Kitsun',
    'AmaterasuWolf_Dark': 'Kitsun Noct',
    'AmaterasuWolf_Dark_Quest_Enemy': 'Kitsun Noct',
    'AmaterasuWolf_Dark_Quest_Friend': 'Kitsun Noct',
    'Anubis': 'Anubis',
    'BOSS_Alpaca': 'Pompous Shanks Melpaca',
    'BOSS_AmaterasuWolf': 'Guardian of the Azure Flame Kitsun',
    'BOSS_AmaterasuWolf_Dark': 'Guardian of the Dark Flame Kitsun Noct',
    'BOSS_BadCatgirl': 'Night Shade Hunter Nyafia',
    'BOSS_Baphomet': 'Hyena of the Wild Incineram',
    'BOSS_Baphomet_Dark': 'Hyena of the Darkest Night Incineram Noct',
    'BOSS_Bastet': 'Noble Glimmer Mau',
    'BOSS_Bastet_Ice': 'Serene Glimmer Mau Cryst',
    'BOSS_BerryGoat': 'Walking Farm Caprity',
    'BOSS_BerryGoat_Dark': 'Tainted Farm Caprity Noct',
    'BOSS_BirdDragon': 'Aerial Marauder Vanwyrm',
    'BOSS_BirdDragon_Ice': 'Marauder of Frozen Skies Vanwyrm Cryst',
    'BOSS_BlackCentaur': 'Dark Knight of Legend Necromus',
    'BOSS_BlackGriffon': 'Unknown Life Form Shadowbeak',
    'BOSS_BlackGriffon_BossRush': 'Unknown Life Form Shadowbeak',
    'BOSS_BlackMetalDragon': 'Monarch of the Steel Dragon Astegon',
    'BOSS_BlackPuppy': 'Jet-Black Little Hero Smokie',
    'BOSS_BlackPuppy_Ice': 'Chilly Little Hero Smokie Cryst',
    'BOSS_BlueDragon': 'Lady of the Lake Azurobe',
    'BOSS_BlueDragon_Ice': 'Lady of the Frozen Lake Azurobe Cryst',
    'BOSS_BluePlatypus': 'Rowdy Wave Ripper Fuack',
    'BOSS_BluePlatypus_Fire': 'Runaway Wave Rider Fuack Ignis',
    'BOSS_BlueSkyDragon': 'Water God Shaolong',
    'BOSS_BlueSkyDragon_BossRush': 'Water God Shaolong',
    'BOSS_BlueThunderHorse': 'Blue Lightning Steed Azurmane',
    'BOSS_BlueberryFairy': 'Indigo Handmaiden Prunelia',
    'BOSS_Boar': 'Woodland Ruffian Rushoar',
    'BOSS_BrownRabbit': 'Indomitable Racer Lapiron',
    'BOSS_CactusDoll': 'Prickly Welcome Needoll',
    'BOSS_CactusDoll_Dark': 'Binding Spines Needoll Noct',
    'BOSS_CandleGhost': 'Flickering Flame Sootseer',
    'BOSS_CaptainPenguin': 'Pioneer of the Frozen Sea Penking',
    'BOSS_CaptainPenguin_Black': 'Pioneer of the Black Penking Lux',
    'BOSS_Carbunclo': 'Coward of the Steppe Lifmunk',
    'BOSS_CatBat': 'Trickster Tombat',
    'BOSS_CatMage': 'Phantasmal Feline Katress',
    'BOSS_CatMage_Fire': 'Fire Licked Feline Katress Ignis',
    'BOSS_CatVampire': 'Gloom-Shrouded Bloodsucker Felbat',
    'BOSS_ChickenPal': 'Plump & Juicy Chikipi',
    'BOSS_ClioneTwins': 'Miraculously Close Amione',
    'BOSS_CloverFairy': 'Dubiously Lucky Clovee',
    'BOSS_ClownRabbit': 'Illusionist Cottontail Dupin',
    'BOSS_ColorfulBird': 'Boom or Bust Tocotoco',
    'BOSS_CowPal': 'Grade A Beef Mozzarina',
    'BOSS_CubeTurtle': 'Sandsea Monolith Tetroise',
    'BOSS_CubeTurtle_Neutral': 'Sandsea Wardenstone Tetroise Primo',
    'BOSS_CuteButterfly': 'Butterfly Promenade Cinnamoth',
    'BOSS_CuteFox': 'Star of the Steppe Vixy',
    'BOSS_CuteMole': 'Underground Explorer Fuddler',
    'BOSS_DandelionGirl': 'Windborne Seedling Souffline',
    'BOSS_DarkAlien': 'Interloper from Outer Space Xenovader',
    'BOSS_DarkCrow': 'Shadow-Cloaked Schemer Cawgnito',
    'BOSS_DarkFlameFox': 'Flickering Shadow Majex',
    'BOSS_DarkMechaDragon': 'Invader from Space Xenolord',
    'BOSS_DarkMutant': 'BOSS_NAME_DarkMutant DarkMutant',
    'BOSS_DarkScorpion': 'Unstoppable Stinger Menasting',
    'BOSS_DarkScorpion_Ground': 'Gold-Piercing Spear Menasting Terra',
    'BOSS_Deer': 'Protector of the Herd Eikthyrdeer',
    'BOSS_Deer_Ground': 'Antler of Gold Eikthyrdeer Terra',
    'BOSS_DomeArmorDragon': 'Guardian of Luminous Trails Aegidron',
    'BOSS_DreamDemon': 'Daedream',
    'BOSS_DrillGame': 'Drilling Machine Digtoise',
    'BOSS_Eagle': 'Proud Courier Galeclaw',
    'BOSS_ElecCat': 'Livewire Tabby Sparkit',
    'BOSS_ElecLion': 'BOSS_NAME_ElecLion Boltmane',
    'BOSS_ElecLizard': 'Shockingly Laid-Back Slowatt',
    'BOSS_ElecPanda': 'Claws of Lightning Grizzbolt',
    'BOSS_ElecPanda_BossRush': 'Claws of Lightning Grizzbolt',
    'BOSS_ElecPomeranian': 'Sulky Static Puffolt',
    'BOSS_ElecSnail': 'Sluggish Blue Bolt Snock',
    'BOSS_ElecSnail_Ground': 'Sluggish Dazzling Flash Snock Lux',
    'BOSS_FairyDragon': 'Gentle Sky Dragon Elphidran',
    'BOSS_FairyDragon_Water': 'Beast of the Tides Elphidran Aqua',
    'BOSS_FeatherOstrich': 'Brilliant Steps Dazemu',
    'BOSS_FengyunDeeper': 'Drifting Cloud Fenglope',
    'BOSS_FengyunDeeper_Electric': 'Drifting Thundercloud Fenglope Lux',
    'BOSS_FireKirin': 'Steed of Flames Pyrin',
    'BOSS_FireKirin_Dark': 'Steed of Darkness Pyrin Noct',
    'BOSS_FlameBambi': 'Chief of the Herd Rooby',
    'BOSS_FlameBuffalo': 'Blazing Brute Arsox',
    'BOSS_FlowerDinosaur': 'Guardian of Blossoming Gardens Dinossom',
    'BOSS_FlowerDinosaur_Electric': 'Guardian of Lightning Dinossom Lux',
    'BOSS_FlowerDoll': 'Lady of the Flower Garden Petallia',
    'BOSS_FlowerDoll_Fire': 'Lady of the Ashen Wastes Petallia Ignis',
    'BOSS_FlowerPrince': 'Bewitching Lurker Dandilord',
    'BOSS_FlowerRabbit': 'Star of the Flower Beds Flopie',
    'BOSS_FluffyBird': 'Totally Toasty Muffly',
    'BOSS_FlyingManta': 'Soaring Skyfish Celaray',
    'BOSS_FlyingManta_Thunder': 'Sky-Swimming Fish Celaray Lux',
    'BOSS_FoxExorcist': 'Self-Serving Seer Flaracle',
    'BOSS_FoxMage': 'Fire Licked Furball Wixen',
    'BOSS_FoxMage_Dark': 'Phantasmal Furball Wixen Noct',
    'BOSS_Ganesha': 'Adorable Watering Can Teafant',
    'BOSS_Garm': 'Hunter of the Steppe Direhowl',
    'BOSS_GhostAnglerfish': 'Temptation in the Deep Ghangler',
    'BOSS_GhostAnglerfish_Fire': 'Longing in the Deep Ghangler Ignis',
    'BOSS_GhostBeast': 'Messenger of Death Maraith',
    'BOSS_GhostBlackCat': 'Adorable Phantom Thief Wispaw',
    'BOSS_GhostDragon': 'Wings of Freedom Eidrolon',
    'BOSS_GhostDragon_Fire': 'Wings of Distrust Eidrolon Ignis',
    'BOSS_GhostRabbit': 'Soul of the Dark Rabbit Nitemary',
    'BOSS_GhostRabbit_Grass': 'Soul of the Green Rabbit Nitemary Botan',
    'BOSS_GoldenHorse': 'Guardian Beast of Twilight Gildane',
    'BOSS_Gorilla': 'Jungle Punk Gorirat',
    'BOSS_Gorilla_Ground': 'Up for a Brawl Gorirat Terra',
    'BOSS_GrassGolem': 'Twinhearted Azure Construct Dualith',
    'BOSS_GrassGolem_Dark': 'Twinhearted Violet Construct Dualith Noct',
    'BOSS_GrassMammoth': 'King of the Forest Mammorest',
    'BOSS_GrassMammoth_Ice': 'Frozen King Mammorest Cryst',
    'BOSS_GrassMinotaur': 'Verdant Minotaur Elgrove',
    'BOSS_GrassMinotaur_Ice': 'Frozen Minotaur Elgrove Cryst',
    'BOSS_GrassPanda': 'Guardian of the Forest Mossanda',
    'BOSS_GrassPanda_Electric': 'Inheritor of the Storm Mossanda Lux',
    'BOSS_GrassRabbitMan': 'Gale of the Forest Verdash',
    'BOSS_GrimGirl': 'Crimson Butcher Splatterina',
    'BOSS_GuardianDog': 'Unwavering Loyalty Yakumo',
    'BOSS_HadesBird': 'Wings of The Underworld Helzephyr',
    'BOSS_HadesBird_Electric': 'Wings of Thunder Helzephyr Lux',
    'BOSS_HawkBird': 'Wings of the Firmament Nitewing',
    'BOSS_Hedgehog': "Don't Touch! Jolthog",
    'BOSS_Hedgehog_Ice': 'Watch Your Feet! Jolthog Cryst',
    'BOSS_HerculesBeetle': 'Unyielding Colossus Warsect',
    'BOSS_HerculesBeetle_Ground': 'Golden Armor Warrior Warsect Terra',
    'BOSS_HoodGhost': 'Vanishing Master Hoodle',
    'BOSS_Horus': 'Sentinel of Dawn Faleris',
    'BOSS_Horus_BossRush': 'Sentinel of Dawn Faleris',
    'BOSS_Horus_Water': 'Sentinel of the Tides Faleris Aqua',
    'BOSS_IceCrocodile': 'Walking Refrigerator Munchill',
    'BOSS_IceDeer': 'Frosthorn Beast Reindrix',
    'BOSS_IceFox': 'Claws of Ice Foxcicle',
    'BOSS_IceHorse': 'Legendary Steed of Ice Frostallion',
    'BOSS_IceHorse_Dark': 'Legendary Steed of Darkness Frostallion Noct',
    'BOSS_IceNarwhal': 'Nice Ice Lance Whalaska',
    'BOSS_IceNarwhal_Fire': 'Nice Crimson Lance Whalaska Ignis',
    'BOSS_IceSeal': 'Idol on Ice Polapup',
    'BOSS_IceSeal_Ground': 'Star of the Dunes Polapup Terra',
    'BOSS_IceWitch': 'Icy Smile Icelyn',
    'BOSS_JellyfishFairy': 'Sunlight Drifter Jelliette',
    'BOSS_JellyfishGhost': 'Shade Drifter Jellroy',
    'BOSS_JetDragon': 'Legendary Celestial Dragon Jetragon',
    'BOSS_KabukiMan': 'Scorching Ovation Renjishi',
    'BOSS_Kelpie': 'Child of the Deep Kelpsea',
    'BOSS_Kelpie_Fire': 'Child of Molten Depths Kelpsea Ignis',
    'BOSS_KendoFrog': 'Harakiri Master Croajiro',
    'BOSS_KendoFrog_Dark': 'Natural Born Killer Croajiro Noct',
    'BOSS_KingAlpaca': 'Supreme Fluff Commander Kingpaca',
    'BOSS_KingAlpaca_Ice': 'Azure Fluff Commander Kingpaca Cryst',
    'BOSS_KingBahamut': 'Cursed Tyrant Blazamut',
    'BOSS_KingBahamut_Dragon': 'Incarnation of the Eternal Flame Blazamut Ryu',
    'BOSS_KingSunfish': 'Buoyant Baron Solmora',
    'BOSS_KingSunfish_Thunder': 'Buoyant Brigadier Solmora Lux',
    'BOSS_KingWhale_otomo': 'Panthalus',
    'BOSS_Kirin': 'Swift Deity Univolt',
    'BOSS_Kirin_Ice': 'Blustery Blizzard Fiend Univolt Cryst',
    'BOSS_Kitsunebi': 'Revealer of Paths Foxparks',
    'BOSS_Kitsunebi_Ice': 'Icy Blossom Voyager Foxparks Cryst',
    'BOSS_LanternButler': 'Revealer of Truths Loomen',
    'BOSS_LavaGirl': 'Molten Daughter Flambelle',
    'BOSS_LazyCatfish': 'Perpetual Procrastinator Dumud',
    'BOSS_LazyCatfish_Gold': 'Piece of Cake Dumud Gild',
    'BOSS_LazyDragon': 'Gluttonous Dragon Relaxaurus',
    'BOSS_LazyDragon_Electric': 'Gluttonous Thunder Dragon Relaxaurus Lux',
    'BOSS_LeafMomonga': 'Percussive Maintenance Herbil',
    'BOSS_LeafPrincess': 'Primal Source of Hay Fever Lullu',
    'BOSS_LegendDeer': 'King of Salvation Hartalis',
    'BOSS_LilyQueen': 'Lily Empress Lyleen',
    'BOSS_LilyQueen_BossRush': 'Lily Empress Lyleen',
    'BOSS_LilyQueen_Dark': 'Empress of the Abyss Lyleen Noct',
    'BOSS_LittleBriarRose': 'Thorny Rose Bristla',
    'BOSS_LizardMan': 'Self-Proclaimed Genius Leezpunk',
    'BOSS_LizardMan_Fire': 'Self-Proclaimed Fashionista Leezpunk Ignis',
    'BOSS_LongCat': 'Plays Both Sides Valentail',
    'BOSS_LotusDragon': 'Pure Bloom Dragon Ophydia',
    'BOSS_Manticore': 'Crimson Goliath Blazehowl',
    'BOSS_Manticore_Dark': 'Inferno Goliath Blazehowl Noct',
    'BOSS_MimicDog': 'Treasure Trove Mimog',
    'BOSS_Monkey': 'Dexterous Primate Tanzee',
    'BOSS_Monkey_Fire': 'Flame Aficionado Tanzee Ignis',
    'BOSS_MonochromeQueen': 'Veiled Dancer of Dusk Solenne',
    'BOSS_MoonChild': 'Mantle of the Night Sky Wistella',
    'BOSS_MoonQueen': 'Crescent of the Darkest Night Selyne',
    'BOSS_MoonQueen_BossRush': 'Crescent of the Darkest Night Selyne',
    'BOSS_MopBaby': 'Curious Floof Swee',
    'BOSS_MopKing': 'King of the Floof Sweepa',
    'BOSS_Mothman': 'Immortal Shade Silvance',
    'BOSS_MummyPal': 'Golden Blade of Duat Gildra',
    'BOSS_MushroomDragon': 'Creeping Mushroom Shroomer',
    'BOSS_MushroomDragon_Dark': 'Dangerous Mushroom Shroomer Noct',
    'BOSS_MushroomLady': 'Cute as a Button Mycora',
    'BOSS_Mutant': 'Extraterrestrial Lunaris',
    'BOSS_MysteryMask': 'Hundred-Faced Apostle Omascul',
    'BOSS_NaughtyCat': 'Marshmallow Body Grintale',
    'BOSS_NegativeKoala': 'Several Sleepless Nights Later Depresso',
    'BOSS_NegativeOctopus': 'Emotionless Killamari',
    'BOSS_NegativeOctopus_Neutral': 'Devoid of Emotion Killamari Primo',
    'BOSS_NightBlueHorse': 'Midnight Blue Mane Starryon',
    'BOSS_NightBlueHorse_Neutral': 'Silvermane Starryon Primo',
    'BOSS_NightFox': 'Dusken Aristocrat Nox',
    'BOSS_NightLady': 'Eclipsed Siren Bellanoir',
    'BOSS_NightLady_Dark': 'Twilight Siren Bellanoir Libero',
    'BOSS_OctopusGirl': 'Trickster of the Sea Gloopie',
    'BOSS_OctopusGirl_Neutral': 'Everyday Trickster Gloopie Primo',
    'BOSS_OniGhostGirl': 'Freakily Cute Bakemi',
    'BOSS_PandaGirl': 'Hardcore Heartbreaker Leafan',
    'BOSS_Penguin': 'Ate Too Much Pengullet',
    'BOSS_Penguin_Electric': 'Had One Too Many Pengullet Lux',
    'BOSS_PinkCat': "The Cat's Pajamas Cattiva",
    'BOSS_PinkLizard': 'Pal on the Prowl Lovander',
    'BOSS_PinkRabbit': 'Heart-Melting Smile Ribbuny',
    'BOSS_PinkRabbit_Grass': 'Sparkling Smile Ribbuny Botan',
    'BOSS_PlantSlime': 'Suddenly Transformed Gumoss',
    'BOSS_PlantSlime_Flower': 'Gumoss (Flower)',
    'BOSS_Plesiosaur': 'Ancient Bloombringer Braloha',
    'BOSS_PoseidonOrca': 'Legend of the Seas Neptilius',
    'BOSS_PurpleSpider': 'Tactician of the Thread Realm Tarantriss',
    'BOSS_QueenBee': 'Empress of the Hive Elizabee',
    'BOSS_RaijinDaughter': 'Born of the Storm Dazzi',
    'BOSS_RaijinDaughter_Water': 'Born of the Thunderclouds Dazzi Noct',
    'BOSS_RedArmorBird': 'Wings of Inferno Ragnahawk',
    'BOSS_RedFlowerBird': 'Blooming Crooner Tropicaw',
    'BOSS_RobinHood': 'Archer of the Forest Robinquill',
    'BOSS_RobinHood_Ground': 'Archer of the Sands Robinquill Terra',
    'BOSS_RockBeast': 'Shambling Vein Pierdon',
    'BOSS_RockBeast_Ice': 'Shuffling Glacier Pierdon Cryst',
    'BOSS_Ronin': 'Vagrant Warrior Bushi',
    'BOSS_Ronin_Dark': 'Samurai of Darkness Bushi Noct',
    'BOSS_SaintCentaur': 'Holy Knight of Legend Paladius',
    'BOSS_SakuraSaurus': 'Winds of Spring Broncherry',
    'BOSS_SakuraSaurus_Water': 'Waves of Summer Broncherry Aqua',
    'BOSS_SamuraiDog': 'Zealous Alpha Pupperai',
    'BOSS_ScorpionMan': 'Bad Boy Prixter',
    'BOSS_ScorpionMan_Electric': 'Thunderboy Prixter Lux',
    'BOSS_Serpent': "The Ocean's Wrath Surfent",
    'BOSS_Serpent_Ground': "The Desert's Wrath Surfent Terra",
    'BOSS_SharkKid': 'Sea Thug Gobfin',
    'BOSS_SharkKid_Fire': 'Volcano Thug Gobfin Ignis',
    'BOSS_SheepBall': 'Big Floof Lamball',
    'BOSS_SifuDog': 'State of Enlightenment Dogen',
    'BOSS_SkyDragon': 'Snow-White Soarer Quivern',
    'BOSS_SkyDragon_Grass': 'Evergreen Flyer Quivern Botan',
    'BOSS_SleeveRabbit': 'Pristine Fisticuffs Lapure',
    'BOSS_SmallArmadillo': 'Armored to the Teeth Kikit',
    'BOSS_SmallYeti': 'Alpine Dwarf Snugloo',
    'BOSS_SnakeGirl': 'Salon Shunner Venusa',
    'BOSS_SnowPeafowl': 'Snowlaced Feather Mantle Frostplume',
    'BOSS_SnowTigerBeastman': 'King of Frostfang Bastigor',
    'BOSS_SnowTigerBeastman_BossRush': 'King of Frostfang Bastigor',
    'BOSS_SoldierBee': 'Guardian Commander Beegarde',
    'BOSS_StuffedShark': 'Eyes from the Abyss Finsider',
    'BOSS_StuffedShark_Fire': 'Eyes from the Flames Finsider Ignis',
    'BOSS_SumoDog': "Bangin' Yokozuna Bulldosu",
    'BOSS_Suzaku': 'Ruler of the Crimson Dawn Suzaku',
    'BOSS_Suzaku_Water': 'Ruler of the Cobalt Dusk Suzaku Aqua',
    'BOSS_SweetsSheep': 'Giant Cotton Candy Woolipop',
    'BOSS_SweetsSheep_Ground': 'King-Sized Confection Woolipop Terra',
    'BOSS_SwordCutlassfish': 'Splashy Determined Draw Skutlass',
    'BOSS_SwordCutlassfish_Fire': 'Blazing Determined Draw Skutlass Ignis',
    'BOSS_TentacleTurtle': 'Mini Fortress Turtacle',
    'BOSS_TentacleTurtle_Ground': 'Golden Fortress Turtacle Terra',
    'BOSS_ThiefBird': 'Pitch Black Pilferer Roujay',
    'BOSS_ThunderBird': 'Wings of Thunder Beakon',
    'BOSS_ThunderBird_Ice': 'Wings of Frost Beakon Cryst',
    'BOSS_ThunderDog': 'Electro-Charged Zoomies Rayhound',
    'BOSS_ThunderDog_Ice': 'Frost-Fringed Zoomies Rayhound Cryst',
    'BOSS_ThunderDragonMan': 'Roaring Thunder Orserk',
    'BOSS_ThunderDragonMan_BossRush': 'Roaring Thunder Orserk',
    'BOSS_ThunderFluffyBird': 'Buzzy Bundle Dynamoff',
    'BOSS_TropicalOstrich': 'No Dance, No Life Palumba',
    'BOSS_Umihebi': 'Emperor of the Sea Jormuntide',
    'BOSS_Umihebi_Fire': 'Volcanic Emperor Jormuntide Ignis',
    'BOSS_VenusFlytrap': 'Open-Minded Glutton Carnibora',
    'BOSS_VioletFairy': 'Voice of the Violets Vaelet',
    'BOSS_VolcanicMonster': 'Lava-Devouring Juggernaut Reptyro',
    'BOSS_VolcanicMonster_Ice': 'Ice-Breaking Juggernaut Reptyro Cryst',
    'BOSS_VolcanoDragon': 'Scorched Wanderer Moldron',
    'BOSS_VolcanoDragon_Ice': 'Frigid Voyager Moldron Cryst',
    'BOSS_WeaselDragon': 'Dancer on the Steppe Chillet',
    'BOSS_WeaselDragon_Fire': 'Cherry Blossom Dancer Chillet Ignis',
    'BOSS_Werewolf': 'Enraptured by Moonlight Loupmoon',
    'BOSS_Werewolf_Ice': 'Enraptured by the Frozen Moonlight Loupmoon Cryst',
    'BOSS_WhiteAlienDragon': 'Planet-Devouring Dragon Xenogard',
    'BOSS_WhiteDeer': 'Beast of Salvation Celesdir',
    'BOSS_WhiteDeer_Dark': 'Beast of Chaos Celesdir Noct',
    'BOSS_WhiteMoth': 'Pallid Lady Sibelyx',
    'BOSS_WhiteMoth_Neutral': 'Gilded Lady Sibelyx Primo',
    'BOSS_WhiteShieldDragon': 'Guardian Dragon of Ironclad Silvegis',
    'BOSS_WhiteTiger': 'Predator of Snowy Peaks Cryolinx',
    'BOSS_WhiteTiger_Ground': 'Predator of the Earth Cryolinx Terra',
    'BOSS_WindChimes': 'Bringer of Luck Hangyu',
    'BOSS_WindChimes_Ice': 'Glacial Harbinger Hangyu Cryst',
    'BOSS_WingGolem': 'Suit of Armor Knocklem',
    'BOSS_WingGolem_Fire': 'Blazing Suit of Armor Knocklem Ignis',
    'BOSS_WizardOwl': 'Purveyor of Wisdom Hoocrates',
    'BOSS_WoolFox': 'Darling Furball Cremis',
    'BOSS_WorldTreeDragon': 'Astralym',
    'BOSS_YakushimaBoss001': 'Eye of Cthulhu',
    'BOSS_Yeti': 'Guardian of the Snowy Mountain Wumpo',
    'BOSS_Yeti_Grass': 'Guardian of the Grassy Fields Wumpo Botan',
    'BadCatgirl': 'Nyafia',
    'Baphomet': 'Incineram',
    'Baphomet_Dark': 'Incineram Noct',
    'Baphomet_Dark_Oilrig': 'Incineram Noct',
    'Bastet': 'Mau',
    'Bastet_Ice': 'Mau Cryst',
    'BerryGoat': 'Caprity',
    'BerryGoat_Dark': 'Caprity Noct',
    'BirdDragon': 'Vanwyrm',
    'BirdDragon_Ice': 'Vanwyrm Cryst',
    'BlackCentaur': 'Necromus',
    'BlackFurDragon': 'Dragostrophe',
    'BlackGriffon': 'Shadowbeak',
    'BlackMetalDragon': 'Astegon',
    'BlackPuppy': 'Smokie',
    'BlackPuppy_Ice': 'Smokie Cryst',
    'BlueDragon': 'Azurobe',
    'BlueDragon_Ice': 'Azurobe Cryst',
    'BluePlatypus': 'Fuack',
    'BluePlatypus_Fire': 'Fuack Ignis',
    'BlueSkyDragon': 'Shaolong',
    'BlueThunderHorse': 'Azurmane',
    'BlueberryFairy': 'Prunelia',
    'Boar': 'Rushoar',
    'Boss_Anubis': 'Guardian of the Dark Sun Anubis',
    'BrownRabbit': 'Lapiron',
    'CactusDoll': 'Needoll',
    'CactusDoll_Dark': 'Needoll Noct',
    'CandleGhost': 'Sootseer',
    'CaptainPenguin': 'Penking',
    'CaptainPenguin_Black': 'Penking Lux',
    'Carbunclo': 'Lifmunk',
    'CatBat': 'Tombat',
    'CatMage': 'Katress',
    'CatMage_Fire': 'Katress Ignis',
    'CatVampire': 'Felbat',
    'ChickenPal': 'Chikipi',
    'ClioneTwins': 'Amione',
    'CloverFairy': 'Clovee',
    'ClownRabbit': 'Dupin',
    'ColorfulBird': 'Tocotoco',
    'CowPal': 'Mozzarina',
    'CubeTurtle': 'Tetroise',
    'CubeTurtle_Neutral': 'Tetroise Primo',
    'CuteButterfly': 'Cinnamoth',
    'CuteFox': 'Vixy',
    'CuteMole': 'Fuddler',
    'DandelionGirl': 'Souffline',
    'DarkAlien': 'Xenovader',
    'DarkAlien_Oilrig': 'Xenovader',
    'DarkCrow': 'Cawgnito',
    'DarkFlameFox': 'Majex',
    'DarkMechaDragon': 'Xenolord',
    'DarkMutant': 'DarkMutant',
    'DarkScorpion': 'Menasting',
    'DarkScorpion_Ground': 'Menasting Terra',
    'Deer': 'Eikthyrdeer',
    'Deer_Ground': 'Eikthyrdeer Terra',
    'DomeArmorDragon': 'Aegidron',
    'DreamDemon': 'Daedream',
    'DrillGame': 'Digtoise',
    'Eagle': 'Galeclaw',
    'ElecCat': 'Sparkit',
    'ElecLion': 'Boltmane',
    'ElecLizard': 'Slowatt',
    'ElecPanda': 'Grizzbolt',
    'ElecPomeranian': 'Puffolt',
    'ElecSnail': 'Snock',
    'ElecSnail_Ground': 'Snock Lux',
    'FairyDragon': 'Elphidran',
    'FairyDragon_Water': 'Elphidran Aqua',
    'FeatherOstrich': 'Dazemu',
    'FengyunDeeper': 'Fenglope',
    'FengyunDeeper_Electric': 'Fenglope Lux',
    'FireKirin': 'Pyrin',
    'FireKirin_Dark': 'Pyrin Noct',
    'FlameBambi': 'Rooby',
    'FlameBuffalo': 'Arsox',
    'FlowerDinosaur': 'Dinossom',
    'FlowerDinosaur_Electric': 'Dinossom Lux',
    'FlowerDoll': 'Petallia',
    'FlowerDoll_Fire': 'Petallia Ignis',
    'FlowerPrince': 'Dandilord',
    'FlowerRabbit': 'Flopie',
    'FluffyBird': 'Muffly',
    'FlyingManta': 'Celaray',
    'FlyingManta_Thunder': 'Celaray Lux',
    'FoxExorcist': 'Flaracle',
    'FoxMage': 'Wixen',
    'FoxMage_Dark': 'Wixen Noct',
    'GYM_BlackGriffon': 'Victor & Shadowbeak',
    'GYM_BlackGriffon_2': 'Victor & Shadowbeak II',
    'GYM_BlackGriffon_2_Avatar': 'Victor & Shadowbeak',
    'GYM_BlueSkyDragon': 'Auri & Shaolong',
    'GYM_BlueSkyDragon_2': 'Auri & Shaolong II',
    'GYM_ElecPanda': 'Zoe & Grizzbolt',
    'GYM_ElecPanda_2': 'Zoe & Grizzbolt II',
    'GYM_ElecPanda_Otomo': 'Zoe & Grizzbolt',
    'GYM_Horus': 'Marcus & Faleris',
    'GYM_Horus_2': 'Marcus & Faleris II',
    'GYM_LilyQueen': 'Lily & Lyleen',
    'GYM_LilyQueen_2': 'Lily & Lyleen II',
    'GYM_MoonQueen': 'Saya & Selyne',
    'GYM_MoonQueen_2': 'Saya & Selyne II',
    'GYM_MoonQueen_2_Servant': 'Selyne',
    'GYM_SnowTigerBeastman': 'Bjorn & Bastigor',
    'GYM_SnowTigerBeastman_2': 'Bjorn & Bastigor II',
    'GYM_ThunderDragonMan': 'Axel & Orserk',
    'GYM_ThunderDragonMan_2': 'Axel & Orserk II',
    'GYM_WorldTreeDragon': 'Zenara & Astralym',
    'GYM_WorldTreeDragon_2': 'Zenara & Astralym II',
    'Ganesha': 'Teafant',
    'Garm': 'Direhowl',
    'GhostAnglerfish': 'Ghangler',
    'GhostAnglerfish_Fire': 'Ghangler Ignis',
    'GhostBeast': 'Maraith',
    'GhostBlackCat': 'Wispaw',
    'GhostDragon': 'Eidrolon',
    'GhostDragon_Fire': 'Eidrolon Ignis',
    'GhostRabbit': 'Nitemary',
    'GhostRabbit_Grass': 'Nitemary Botan',
    'GoldenHorse': 'Gildane',
    'Gorilla': 'Gorirat',
    'Gorilla_Ground': 'Gorirat Terra',
    'GrassGolem': 'Dualith',
    'GrassGolem_Dark': 'Dualith Noct',
    'GrassMammoth': 'Mammorest',
    'GrassMammoth_Ice': 'Mammorest Cryst',
    'GrassMinotaur': 'Elgrove',
    'GrassMinotaur_Ice': 'Elgrove Cryst',
    'GrassPanda': 'Mossanda',
    'GrassPanda_Electric': 'Mossanda Lux',
    'GrassPanda_Electric_Tower': 'Mossanda Lux',
    'GrassRabbitMan': 'Verdash',
    'GrimGirl': 'Splatterina',
    'GuardianDog': 'Yakumo',
    'HadesBird': 'Helzephyr',
    'HadesBird_Electric': 'Helzephyr Lux',
    'HadesBird_Oilrig': 'Helzephyr',
    'HawkBird': 'Nitewing',
    'Hedgehog': 'Jolthog',
    'Hedgehog_Ice': 'Jolthog Cryst',
    'HerculesBeetle': 'Warsect',
    'HerculesBeetle_Ground': 'Warsect Terra',
    'HoodGhost': 'Hoodle',
    'Horus': 'Faleris',
    'Horus_Oilrig': 'Faleris',
    'Horus_Water': 'Faleris Aqua',
    'IceCrocodile': 'Munchill',
    'IceDeer': 'Reindrix',
    'IceFox': 'Foxcicle',
    'IceHorse': 'Frostallion',
    'IceHorse_Dark': 'Frostallion Noct',
    'IceNarwhal': 'Whalaska',
    'IceNarwhal_Fire': 'Whalaska Ignis',
    'IceSeal': 'Polapup',
    'IceSeal_Ground': 'Polapup Terra',
    'IceWitch': 'Icelyn',
    'JellyfishFairy': 'Jelliette',
    'JellyfishGhost': 'Jellroy',
    'JetDragon': 'Jetragon',
    'KabukiMan': 'Renjishi',
    'Kelpie': 'Kelpsea',
    'Kelpie_Fire': 'Kelpsea Ignis',
    'KendoFrog': 'Croajiro',
    'KendoFrog_Dark': 'Croajiro Noct',
    'KingAlpaca': 'Kingpaca',
    'KingAlpaca_Ice': 'Kingpaca Cryst',
    'KingBahamut': 'Blazamut',
    'KingBahamut_Dragon': 'Blazamut Ryu',
    'KingSunfish': 'Solmora',
    'KingSunfish_Thunder': 'Solmora Lux',
    'KingWhale': 'Panthalus',
    'Kirin': 'Univolt',
    'Kirin_Ice': 'Univolt Cryst',
    'Kitsunebi': 'Foxparks',
    'Kitsunebi_Ice': 'Foxparks Cryst',
    'LanternButler': 'Loomen',
    'LavaGirl': 'Flambelle',
    'LazyCatfish': 'Dumud',
    'LazyCatfish_Gold': 'Dumud Gild',
    'LazyDragon': 'Relaxaurus',
    'LazyDragon_Electric': 'Relaxaurus Lux',
    'LazyDragon_Electric_Tower': 'Relaxaurus Lux',
    'LeafMomonga': 'Herbil',
    'LeafPrincess': 'Lullu',
    'LegendDeer': 'Hartalis',
    'LilyQueen': 'Lyleen',
    'LilyQueen_Dark': 'Lyleen Noct',
    'LittleBriarRose': 'Bristla',
    'LizardMan': 'Leezpunk',
    'LizardMan_Fire': 'Leezpunk Ignis',
    'LizardMan_Oilrig': 'Leezpunk',
    'LongCat': 'Valentail',
    'LotusDragon': 'Ophydia',
    'Manticore': 'Blazehowl',
    'Manticore_Dark': 'Blazehowl Noct',
    'MimicDog': 'Mimog',
    'Monkey': 'Tanzee',
    'Monkey_Fire': 'Tanzee Ignis',
    'MonochromeQueen': 'Solenne',
    'MoonChild': 'Wistella',
    'MoonQueen': 'Selyne',
    'MopBaby': 'Swee',
    'MopKing': 'Sweepa',
    'Mothman': 'Silvance',
    'MummyPal': 'Gildra',
    'MushroomDragon': 'Shroomer',
    'MushroomDragon_Dark': 'Shroomer Noct',
    'MushroomLady': 'Mycora',
    'Mutant': 'Lunaris',
    'MysteryMask': 'Omascul',
    'NaughtyCat': 'Grintale',
    'NegativeKoala': 'Depresso',
    'NegativeOctopus': 'Killamari',
    'NegativeOctopus_Neutral': 'Killamari Primo',
    'NightBlueHorse': 'Starryon',
    'NightBlueHorse_Neutral': 'Starryon Primo',
    'NightFox': 'Nox',
    'NightLady': 'Bellanoir',
    'NightLady_Dark': 'Bellanoir Libero',
    'OctopusGirl': 'Gloopie',
    'OctopusGirl_Neutral': 'Gloopie Primo',
    'OniGhostGirl': 'Bakemi',
    'POLICE_HawkBird': 'PIDF Rider',
    'POLICE_ThunderDog': 'PIDF Rider',
    'PREDATOR_AmaterasuWolf': 'Rampaging Kitsun',
    'PREDATOR_Baphomet_Dark': 'Rampaging Incineram Noct',
    'PREDATOR_BirdDragon': 'Rampaging Vanwyrm',
    'PREDATOR_CandleGhost': 'Rampaging Sootseer',
    'PREDATOR_DarkScorpion': 'Rampaging Menasting',
    'PREDATOR_DrillGame': 'Rampaging Digtoise',
    'PREDATOR_FairyDragon': 'Rampaging Elphidran',
    'PREDATOR_FeatherOstrich': 'Rampaging Dazemu',
    'PREDATOR_FlowerDinosaur': 'Rampaging Dinossom',
    'PREDATOR_Garm': 'Rampaging Direhowl',
    'PREDATOR_GhostBeast': 'Rampaging Maraith',
    'PREDATOR_GoldenHorse': 'Rampaging Gildane',
    'PREDATOR_Gorilla': 'Rampaging Gorirat',
    'PREDATOR_GrassMammoth_Ice': 'Rampaging Mammorest Cryst',
    'PREDATOR_GrassMinotaur_Ice': 'Rampaging Elgrove Cryst',
    'PREDATOR_GrassPanda': 'Rampaging Mossanda',
    'PREDATOR_GrimGirl': 'Rampaging Splatterina',
    'PREDATOR_HadesBird_Electric': 'Rampaging Helzephyr Lux',
    'PREDATOR_Horus_Water': 'Rampaging Faleris Aqua',
    'PREDATOR_LazyDragon': 'Rampaging Relaxaurus',
    'PREDATOR_Manticore_Dark': 'Rampaging Blazehowl Noct',
    'PREDATOR_MonochromeQueen': 'Rampaging Solenne',
    'PREDATOR_MummyPal': 'Rampaging Gildra',
    'PREDATOR_MushroomDragon': 'Rampaging Shroomer',
    'PREDATOR_MysteryMask': 'Rampaging Omascul',
    'PREDATOR_NightBlueHorse': 'Rampaging Starryon',
    'PREDATOR_PandaGirl': 'Rampaging Leafan',
    'PREDATOR_PinkLizard': 'Rampaging Lovander',
    'PREDATOR_PurpleSpider': 'Rampaging Tarantriss',
    'PREDATOR_RedArmorBird': 'Rampaging Ragnahawk',
    'PREDATOR_RedFlowerBird': 'Rampaging Tropicaw',
    'PREDATOR_Ronin_Dark': 'Rampaging Bushi Noct',
    'PREDATOR_ScorpionMan': 'Rampaging Prixter',
    'PREDATOR_SifuDog': 'Rampaging Dogen',
    'PREDATOR_SnakeGirl': 'Rampaging Venusa',
    'PREDATOR_Suzaku': 'Rampaging Suzaku',
    'PREDATOR_ThunderDog': 'Rampaging Rayhound',
    'PREDATOR_Umihebi_Fire': 'Rampaging Jormuntide Ignis',
    'PREDATOR_VolcanicMonster_Ice': 'Rampaging Reptyro Cryst',
    'PREDATOR_VolcanoDragon': 'Rampaging Moldron',
    'PREDATOR_Werewolf_Ice': 'Rampaging Loupmoon Cryst',
    'PREDATOR_WhiteTiger_Ground': 'Rampaging Cryolinx Terra',
    'PREDATOR_Yeti': 'Rampaging Wumpo',
    'PandaGirl': 'Leafan',
    'Penguin': 'Pengullet',
    'Penguin_Electric': 'Pengullet Lux',
    'PinkCat': 'Cattiva',
    'PinkLizard': 'Lovander',
    'PinkRabbit': 'Ribbuny',
    'PinkRabbit_Grass': 'Ribbuny Botan',
    'PlantSlime': 'Gumoss',
    'PlantSlime_Flower': 'Gumoss (Flower)',
    'Plesiosaur': 'Braloha',
    'PoseidonOrca': 'Neptilius',
    'PurpleSpider': 'Tarantriss',
    'QueenBee': 'Elizabee',
    'Quest_Farmer03_PinkCat': 'Cattiva',
    'Quest_Farmer03_SheepBall': 'Lamball',
    'RAID_DarkMechaDragon': 'Invader from Space Xenolord',
    'RAID_DarkMechaDragon_2': 'Invader from Space (Ultra) Xenolord',
    'RAID_KingBahamut_Dragon': 'Incarnation of the Eternal Flame Blazamut Ryu',
    'RAID_KingBahamut_Dragon_2': 'Incarnation of the Eternal Flame (Ultra) Blazamut Ryu',
    'RAID_LegendDeer': 'King of Salvation Hartalis',
    'RAID_LegendDeer_2': 'King of Salvation Hartalis',
    'RAID_NightLady': 'Eclipsed Siren Bellanoir',
    'RAID_NightLady_Dark': 'Twilight Siren Bellanoir Libero',
    'RAID_NightLady_Dark_2': 'Twilight Siren (Ultra) Bellanoir Libero',
    'RAID_YakushimaBoss001_Green': 'True Eye of Cthulhu',
    'RAID_YakushimaBoss001_Green_2': 'True Eye of Cthulhu (Ultra)',
    'RAID_YakushimaBoss002': 'Moon Lord',
    'RAID_YakushimaBoss002_2': 'Moon Lord (Ultra)',
    'RAID_YakushimaBoss002_Hand_Left': 'Moon Lord',
    'RAID_YakushimaBoss002_Hand_Left_2': 'Moon Lord (Ultra)',
    'RAID_YakushimaBoss002_Hand_Right': 'Moon Lord',
    'RAID_YakushimaBoss002_Hand_Right_2': 'Moon Lord (Ultra)',
    'RAID_YakushimaBoss002_Head': 'Moon Lord',
    'RAID_YakushimaBoss002_Head_2': 'Moon Lord (Ultra)',
    'RaijinDaughter': 'Dazzi',
    'RaijinDaughter_Water': 'Dazzi Noct',
    'RedArmorBird': 'Ragnahawk',
    'RedFlowerBird': 'Tropicaw',
    'RobinHood': 'Robinquill',
    'RobinHood_Ground': 'Robinquill Terra',
    'RockBeast': 'Pierdon',
    'RockBeast_Ice': 'Pierdon Cryst',
    'Ronin': 'Bushi',
    'Ronin_Dark': 'Bushi Noct',
    'SUMMON_DarkAlien': 'Xenovader',
    'SUMMON_DarkAlien_MAX': 'Xenovader',
    'SUMMON_WhiteAlienDragon': 'Xenogard',
    'SUMMON_WhiteAlienDragon_MAX': 'Xenogard',
    'SaintCentaur': 'Paladius',
    'SakuraSaurus': 'Broncherry',
    'SakuraSaurus_Water': 'Broncherry Aqua',
    'SamuraiDog': 'Pupperai',
    'ScorpionMan': 'Prixter',
    'ScorpionMan_Electric': 'Prixter Lux',
    'Serpent': 'Surfent',
    'Serpent_Ground': 'Surfent Terra',
    'SharkKid': 'Gobfin',
    'SharkKid_Fire': 'Gobfin Ignis',
    'SheepBall': 'Lamball',
    'SifuDog': 'Dogen',
    'SkyDragon': 'Quivern',
    'SkyDragon_Grass': 'Quivern Botan',
    'SleeveRabbit': 'Lapure',
    'SmallArmadillo': 'Kikit',
    'SmallYeti': 'Snugloo',
    'SnakeGirl': 'Venusa',
    'SnowPeafowl': 'Frostplume',
    'SnowTigerBeastman': 'Bastigor',
    'SoldierBee': 'Beegarde',
    'StuffedShark': 'Finsider',
    'StuffedShark_Fire': 'Finsider Ignis',
    'SumoDog': 'Bulldosu',
    'Suzaku': 'Suzaku',
    'Suzaku_Water': 'Suzaku Aqua',
    'SweetsSheep': 'Woolipop',
    'SweetsSheep_Ground': 'Woolipop Terra',
    'SwordCutlassfish': 'Skutlass',
    'SwordCutlassfish_Fire': 'Skutlass Ignis',
    'TentacleTurtle': 'Turtacle',
    'TentacleTurtle_Ground': 'Turtacle Terra',
    'ThiefBird': 'Roujay',
    'ThunderBird': 'Beakon',
    'ThunderBird_Ice': 'Beakon Cryst',
    'ThunderDog': 'Rayhound',
    'ThunderDog_Ice': 'Rayhound Cryst',
    'ThunderDragonMan': 'Orserk',
    'ThunderFluffyBird': 'Dynamoff',
    'TropicalOstrich': 'Palumba',
    'Umihebi': 'Jormuntide',
    'Umihebi_Fire': 'Jormuntide Ignis',
    'VenusFlytrap': 'Carnibora',
    'VioletFairy': 'Vaelet',
    'VolcanicMonster': 'Reptyro',
    'VolcanicMonster_Ice': 'Reptyro Cryst',
    'VolcanoDragon': 'Moldron',
    'VolcanoDragon_Ice': 'Moldron Cryst',
    'WeaselDragon': 'Chillet',
    'WeaselDragon_Fire': 'Chillet Ignis',
    'Werewolf': 'Loupmoon',
    'Werewolf_Ice': 'Loupmoon Cryst',
    'WhiteAlienDragon': 'Xenogard',
    'WhiteDeer': 'Celesdir',
    'WhiteDeer_Dark': 'Celesdir Noct',
    'WhiteMoth': 'Sibelyx',
    'WhiteMoth_Neutral': 'Sibelyx Primo',
    'WhiteShieldDragon': 'Silvegis',
    'WhiteTiger': 'Cryolinx',
    'WhiteTiger_Ground': 'Cryolinx Terra',
    'WindChimes': 'Hangyu',
    'WindChimes_Ice': 'Hangyu Cryst',
    'WingGolem': 'Knocklem',
    'WingGolem_Fire': 'Knocklem Ignis',
    'WingGolem_Oilrig': 'Knocklem',
    'WizardOwl': 'Hoocrates',
    'WoolFox': 'Cremis',
    'WorldTreeDragon': 'Astralym',
    'YakushimaBoss001': 'Eye of Cthulhu',
    'YakushimaBoss001_Small': 'Demon Eye',
    'YakushimaMonster001': 'Green Slime',
    'YakushimaMonster001_Blue': 'Blue Slime',
    'YakushimaMonster001_Pink': 'Illuminant Slime',
    'YakushimaMonster001_Purple': 'Purple Slime',
    'YakushimaMonster001_Rainbow': 'Rainbow Slime',
    'YakushimaMonster001_Red': 'Red Slime',
    'YakushimaMonster002': 'Enchanted Sword',
    'YakushimaMonster003': 'Cave Bat',
    'YakushimaMonster003_Purple': 'Illuminant Bat',
    'Yeti': 'Wumpo',
    'Yeti_Grass': 'Wumpo Botan',
}


def pal_name(character_id):
    """Look up a pal's display name; falls back to the raw CharacterID for
    unmapped/new pals so callers never see a None."""
    if character_id is None:
        return None
    return PAL_NAMES.get(character_id, character_id)
